version: "3.9"

services:
  db:
    image: postgres
    enviroment:
      - POSTGRES_DB = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
  
  web:
    build: .
    command: python manage.py runserver 92.113.25.140:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
