# Generated by Django 5.1 on 2024-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='شماره موبایل', max_length=11, unique=True)),
                ('count', models.IntegerField(help_text='تعداد')),
                ('is_sms', models.BooleanField(default=False, help_text='ایا اس ام اس ارسال شده')),
                ('is_recive', models.BooleanField(default=False, help_text='ایا غذا دریافت کرده')),
                ('sms_date', models.DateField(blank=True, null=True)),
                ('recive_date', models.DateField(blank=True, null=True)),
                ('recive_time', models.TimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گاربران ',
                'verbose_name_plural': 'گاربران',
            },
        ),
    ]
