# Generated by Django 5.1 on 2024-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_peoplemodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemodel',
            name='phone_number',
            field=models.CharField(help_text='شماره موبایل', max_length=13, unique=True),
        ),
    ]
