# Generated by Django 5.1 on 2024-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_peoplemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemodel',
            name='count',
            field=models.IntegerField(help_text='تعداد'),
        ),
    ]
