# Generated by Django 5.1 on 2024-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_peoplemodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemodel',
            name='is_reject',
            field=models.BooleanField(default=False, help_text='ایا برای دریافت آمده'),
        ),
    ]
